name: Notify Telegram
description: "Send a Telegram message"
inputs:
  bot_token:
    required: true
  chat_id:
    required: true
  message:
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -e
        curl -sS -X POST "https://api.telegram.org/bot${{ inputs.token }}/sendMessage" \
          -d chat_id="${{ inputs.to }}" \
          --data-urlencode text="${{ inputs.message }}"